-- Movie Pairs Ranking
-- GitHub: orimor25

-- GOOD RECOMMENDATIONS
-- Nolan directed pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 116556, 10, 'orimor25', 'Memento and Following are both Nolan films built around non-linear storytelling. If you enjoy one, the other is essential viewing.', null); # Memento -> Following
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 210511, 9, 'orimor25', 'Both Nolan films that reward attention to structure. Batman Begins grounds a franchise in realism, Memento does the same for the thriller genre.', null); # Batman Begins -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (160524, 30959, 8, 'orimor25', 'Both early Nolan films exploring guilt and moral compromise. Insomnia is smaller in scale but shares the same psychological intensity as Batman Begins.', null); # Insomnia -> Batman Begins
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (90837, 210511, 9, 'orimor25', 'Doodlebug is a three-minute short already exploring the recursive time loops Nolan would perfect in Memento. Same mind, same obsession.', null); # Doodlebug -> Memento

-- Scorsese directed pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 56304, 10, 'orimor25', 'Goodfellas and Casino are companion pieces about organized crime. Same director, overlapping cast, similar energy but different settings.', null); # Goodfellas -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (209158, 131780, 9, 'orimor25', 'Mean Streets is where Scorsese started exploring the street crime world he would perfect with Goodfellas. Same DNA, earlier stage.', null); # Mean Streets -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 177369, 9, 'orimor25', 'Taxi Driver and King of Comedy are both Scorsese-De Niro studies of obsessive, delusional loners in New York City. Spiritual siblings.', null); # Taxi Driver -> King of Comedy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 326155, 9, 'orimor25', 'Raging Bull and Taxi Driver are both Scorsese-De Niro character studies of self-destructive men. Different worlds, same raw intensity.', null); # Raging Bull -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123849, 56304, 7, 'orimor25', 'Both epic Scorsese films with sprawling casts and period settings. Gangs of New York shares Casino''s ambition even if the eras are completely different.', null); # Gangs of New York -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (7842, 47130, 8, 'orimor25', 'Both dark Scorsese comedies about men spiraling through a single nightmarish experience. After Hours in Manhattan, Bringing Out the Dead in the ambulance.', null); # After Hours -> Bringing Out the Dead

-- Tarantino directed pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 10, 'orimor25', 'Pulp Fiction and Reservoir Dogs are the two films that defined Tarantino. Same dialogue style, same genre-bending confidence, essential pairing.', null); # Pulp Fiction -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 176712, 10, 'orimor25', 'Kill Bill Volumes 1 and 2 are two halves of the same film. You cannot watch one without the other and get the full story.', null); # Kill Bill Vol 1 -> Vol 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 164572, 8, 'orimor25', 'Both Tarantino crime films with overlapping themes of loyalty and double-crossing. Jackie Brown is more restrained but shares the same DNA.', null); # Pulp Fiction -> Jackie Brown
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159665, 276217, 8, 'orimor25', 'Both Tarantino films built around tension-filled conversations that explode into violence. The farmhouse opening of Basterds echoes the heist tension of Dogs.', null); # Inglourious Basterds -> Reservoir Dogs

-- Spielberg directed pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 289109, 10, 'orimor25', 'Both Spielberg WWII films that deal with the human cost of war. Schindler''s List from the civilian side, Saving Private Ryan from the battlefield.', null); # Schindler's List -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159172, 10, 'orimor25', 'Raiders and Last Crusade are the two best Indiana Jones films. Same character, same adventure spirit, the Connery addition makes Crusade a worthy companion.', null); # Raiders -> Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 271095, 9, 'orimor25', 'Jaws and Raiders are peak Spielberg adventure filmmaking. Both build tension masterfully and both made Ford/Scheider into instant stars.', null); # Jaws -> Raiders
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 65811, 9, 'orimor25', 'Both Spielberg films about alien contact where the aliens are not the enemy. E.T. for children, Close Encounters for adults, both with genuine wonder.', null); # E.T. -> Close Encounters
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 117874, 8, 'orimor25', 'Both Spielberg-directed, both Hanks-led, both based on extraordinary real stories. Catch Me If You Can is lighter in tone but shares Forrest Gump''s biographical sweep.', null); # Catch Me If You Can -> Forrest Gump
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (94741, 165961, 9, 'orimor25', 'Duel announced Spielberg as a suspense master and Jaws confirmed it. Both use a barely-seen antagonist to build relentless tension.', null); # Duel -> Jaws
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (359297, 10830, 7, 'orimor25', 'Both alien invasion films that prioritize terror over spectacle. War of the Worlds uses the same visceral approach Alien did but in broad daylight.', null); # War of the Worlds -> Alien

-- Fincher directed pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 291698, 10, 'orimor25', 'Fight Club and Se7en are both dark Fincher films that end with a gut-punch twist. Same director, same tonal darkness, essential pairing.', null); # Fight Club -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 291698, 9, 'orimor25', 'The Game and Se7en are both Fincher films where paranoia drives the plot. If you love one''s atmosphere of dread, the other delivers the same intensity differently.', null); # The Game -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (247579, 123435, 7, 'orimor25', 'Both Fincher thrillers built around confined psychological tension. Panic Room is smaller scale but shares The Game''s claustrophobic suspense.', null); # Panic Room -> The Game

-- LOTR trilogy pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 10, 'orimor25', 'Fellowship and Two Towers are parts one and two of a single story. You cannot stop after the first and not immediately want the second.', null); # Fellowship -> Two Towers
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194500, 10, 'orimor25', 'Two Towers builds the tension that Return of the King resolves. The trilogy is one film split into three and each part depends on the others.', null); # Two Towers -> Return of the King
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 194497, 10, 'orimor25', 'After the epic conclusion of Return of the King, going back to the quiet beginning of Fellowship feels like a completely different experience.', null); # Return of the King -> Fellowship

-- Star Wars pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 10, 'orimor25', 'Empire Strikes Back ends on a cliffhanger that Return of the Jedi resolves. You cannot watch one without needing the other immediately.', null); # Empire -> Jedi
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313478, 7, 'orimor25', 'Revenge of the Sith is the prequel that connects directly to Empire. Seeing the fall of Anakin makes the Vader reveal in Empire hit differently.', null); # Revenge of the Sith -> Empire

-- Bond franchise pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 120574, 10, 'orimor25', 'Goldfinger and From Russia with Love are the two best Connery Bond films. Peak 1960s espionage, both essential for any Bond fan.', null); # Goldfinger -> From Russia with Love
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 192702, 9, 'orimor25', 'GoldenEye and The Living Daylights both reinvented Bond for their respective eras. Different actors but the same ambition to take the character seriously.', null); # GoldenEye -> Living Daylights
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 92573, 9, 'orimor25', 'From Russia with Love and Dr. No are the first two Bond films and the two most grounded in actual espionage rather than spectacle.', null); # From Russia with Love -> Dr. No
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 30959, 8, 'orimor25', 'Both reinvented a franchise hero for a grittier, more realistic era. GoldenEye did it for Bond, Batman Begins did it for Batman. Same creative instinct.', null); # GoldenEye -> Batman Begins

-- Rocky franchise pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280281, 9, 'orimor25', 'Rocky and Rocky II are essentially one story split across two films. The rematch ending only works because you already invested in the first.', null); # Rocky -> Rocky II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 129185, 8, 'orimor25', 'Both underdog stories about warriors fighting for dignity in the arena. Rocky in boxing, Gladiator in the Colosseum, both earn their endings emotionally.', null); # Rocky -> Gladiator

-- Batman pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30955, 8, 'orimor25', 'Batman Begins and Batman 1989 are the two best live-action Batman origin stories. Different tones but both take the character and Gotham seriously.', null); # Batman Begins -> Batman 1989
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30967, 9, 'orimor25', 'Batman and Batman Returns are Burton''s complete vision of Gotham. Returns goes darker and weirder and if you loved the first, the second is essential.', null); # Batman -> Batman Returns
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30976, 30959, 8, 'orimor25', 'Mask of the Phantasm and Batman Begins both explore Bruce Wayne''s origin with real psychological depth. One animated, one live action, both excellent.', null); # Phantasm -> Begins

-- Harry Potter pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 9, 'orimor25', 'Prisoner of Azkaban and Goblet of Fire are when the series matured. Both have genuine stakes and both are directed with more ambition than the first two entries.', null); # Azkaban -> Goblet
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139650, 8, 'orimor25', 'Sorcerer''s Stone and Chamber of Secrets are Columbus''s two entries. If you enjoyed the first''s faithful adaptation, the second continues in exactly the same tone.', null); # Sorcerer's Stone -> Chamber of Secrets

-- Alien franchise pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10920, 10, 'orimor25', 'Alien and Aliens are the perfect genre switch. Scott made a horror film, Cameron made an action film, both are masterpieces in their own right.', null); # Alien -> Aliens

-- Thematic pairs: crime/thriller
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 117874, 8, 'orimor25', 'Both are defining 1990s American films about extraordinary journeys through adversity. Both carried by narration and both leave you emotionally wrung out.', null); # Shawshank -> Forrest Gump
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 112290, 9, 'orimor25', 'Both redefined their decade cinematically. Pulp Fiction broke narrative convention, Fight Club broke the fourth wall. Both are films you discuss for years after.', null); # Pulp Fiction -> Fight Club
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 54209, 7, 'orimor25', 'Both De Niro crime films from the early 1990s. Goodfellas shows the seduction of the mob, Cape Fear shows its terrifying other side.', null); # Goodfellas -> Cape Fear
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (306032, 267038, 8, 'orimor25', 'Both are multi-threaded crime films with sharp dialogue and overlapping plotlines that reward careful attention. Snatch is the British Pulp Fiction.', null); # Snatch -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 56871, 8, 'orimor25', 'Both are slick, entertaining heist/con films with A-list ensembles. The same Spielberg lightness and the same pleasure of watching smart people work.', null); # Ocean's Eleven -> Catch Me If You Can
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 46169, 8, 'orimor25', 'Both are epic historical action films about warriors fighting for freedom. Gladiator in Rome, Braveheart in Scotland, both visceral and emotionally earned.', null); # Gladiator -> Braveheart

-- Thematic pairs: sci-fi
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 210511, 8, 'orimor25', 'Both are intelligent sci-fi films that use their premise to ask genuine philosophical questions rather than just deliver action sequences.', null); # Minority Report -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256839, 10830, 7, 'orimor25', 'Both are survival horror in space with alien creatures. Pitch Black is smaller scale but shares Alien''s emphasis on atmosphere and character over spectacle.', null); # Pitch Black -> Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (61751, 359297, 7, 'orimor25', 'Both are bleaker, more grounded sci-fi films about civilisation under threat. Children of Men and War of the Worlds both treat catastrophe as a lived experience.', null); # Children of Men -> War of the Worlds

-- Thematic pairs: adventure/fantasy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 218219, 8, 'orimor25', 'Both are epic fantasy journeys through richly built worlds. Fellowship and Mononoke are the Western and Eastern peaks of cinematic worldbuilding.', null); # Fellowship -> Mononoke
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131885, 271095, 8, 'orimor25', 'Both are 1980s adventure films driven by treasure hunts and ensemble chemistry. Goonies is Raiders for kids and proud of it.', null); # Goonies -> Raiders
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 271095, 7, 'orimor25', 'Both are swashbuckling adventure films with charismatic leads. Pirates of the Caribbean channels the same spirit as Raiders in a different setting.', null); # Pirates -> Raiders
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 313478, 7, 'orimor25', 'Both are late-1970s/early-1980s space hero films that defined a generation. Superman and Empire Strikes Back are the twin pillars of the genre.', null); # Superman -> Empire

-- Burton/Depp pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 304862, 8, 'orimor25', 'Both Burton-Depp collaborations where Depp plays a misunderstood outsider. Edward Scissorhands in suburbia, Ichabod Crane in rural New York.', null); # Edward Scissorhands -> Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97360, 97727, 8, 'orimor25', 'Both Burton-Depp films about eccentric characters who do not fit in. Ed Wood is a comedy, Scissorhands is a fairy tale, both are about belonging.', null); # Ed Wood -> Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (70959, 59578, 7, 'orimor25', 'Both Burton films with elaborate fantasy production design. Corpse Bride is stop-motion, Charlie is live action, but the visual imagination is the same.', null); # Corpse Bride -> Charlie

-- Animation pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 190869, 8, 'orimor25', 'Both animated films that deal with surprisingly mature emotions underneath colourful surfaces. Toy Story tackles jealousy, Lilo and Stitch tackles family loss.', null); # Toy Story -> Lilo & Stitch
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218219, 174953, 10, 'orimor25', 'Both Miyazaki films about the conflict between nature and civilisation. Mononoke and Nausicaa share a moral complexity rare in animation.', null); # Mononoke -> Nausicaa
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 337166, 7, 'orimor25', 'Both animated films that redefined what the genre could do for their respective studios. Shrek for DreamWorks, Toy Story for Pixar.', null); # Shrek -> Toy Story

-- De Niro pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (330670, 54209, 8, 'orimor25', 'Both feature De Niro as a terrifyingly abusive authority figure. This Boy''s Life as a stepfather, Cape Fear as a stalker, equally uncomfortable to watch.', null); # This Boy's Life -> Cape Fear

-- DiCaprio pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 25192, 8, 'orimor25', 'Both DiCaprio-led biographical films directed by major filmmakers. Catch Me If You Can with Spielberg, Aviator with Scorsese. Both portray obsessive real figures.', null); # Catch Me If You Can -> Aviator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30686, 330670, 8, 'orimor25', 'Both films starring a young DiCaprio in intense dramatic roles before he became a leading man. Basketball Diaries and This Boy''s Life show his raw early talent.', null); # Basketball Diaries -> This Boy's Life

-- Depp non-Burton pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 113506, 6, 'orimor25', 'Both Johnny Depp performances but in completely different modes. Captain Jack is flamboyant comedy, J.M. Barrie is restrained drama. Depp''s range on display.', null); # Pirates -> Finding Neverland
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (41518, 30686, 7, 'orimor25', 'Both films about young men pulled into drug culture and paying the price. Blow and Basketball Diaries share a rise-and-fall structure and refuse to romanticise the lifestyle.', null); # Blow -> Basketball Diaries

-- Lethal Weapon franchise
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188509, 9, 'orimor25', 'Lethal Weapon and Lethal Weapon 2 are the two best entries in the franchise. The addition of Pesci in the sequel adds a comic energy the first film did not need but the second benefits from.', null); # LW -> LW2

-- Mission Impossible pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215880, 8, 'orimor25', 'Mission Impossible and MI3 are the two best entries in the franchise. De Palma started strong and Abrams brought the series back to that level after the Woo detour.', null); # MI -> MI3

-- Superhero pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 142491, 7, 'orimor25', 'Both are superhero films from the mid-2000s that prioritize character over spectacle. Spider-Man 2 and Hellboy both have villains with real emotional depth.', null); # Spider-Man 2 -> Hellboy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 319613, 9, 'orimor25', 'Superman and Superman II are the definitive superhero film pairing. The first builds the myth, the second tests it with real villainy.', null); # Superman -> Superman II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 142492, 9, 'orimor25', 'Hellboy and Hellboy 2 are Del Toro expanding his own creation. The sequel goes further into fantasy and the Golden Army is a stronger visual achievement.', null); # Hellboy -> Hellboy 2

-- Spy Kids franchise
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 210739, 7, 'orimor25', 'Both are family-friendly spy comedies with inventive gadgets and creature designs. Spy Kids is MIB for younger audiences, same playful energy.', null); # Spy Kids -> MIB

-- Horror pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (240327, 259826, 8, 'orimor25', 'Both are 1970s/80s supernatural horror films that build dread through a family under threat. The Omen uses biblical fear, Poltergeist uses suburban fear.', null); # Omen -> Poltergeist

-- Comedy pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291495, 208245, 7, 'orimor25', 'Both are comedies that rely entirely on the charisma of a single lead. Bill Murray carries Scrooged, Mel Gibson carries Maverick, both are effortless fun.', null); # Scrooged -> Maverick
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 66194, 8, 'orimor25', 'Both are 1990s high school comedies based on classic literature. 10 Things from Shakespeare, Clueless from Austen, both smarter than they need to be.', null); # 10 Things -> Clueless

-- Romance pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 151616, 7, 'orimor25', 'Both are light romantic comedies with attractive leads and zero pretensions. Pretty Woman and How to Lose a Guy are comfort viewing in the same category.', null); # Pretty Woman -> How to Lose a Guy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 263360, 7, 'orimor25', 'Both are crowd-pleasing romance blockbusters from the 1990s. Titanic and Pretty Woman are the decade''s two most iconic love stories despite very different stakes.', null); # Titanic -> Pretty Woman

-- War film pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 185628, 7, 'orimor25', 'Both are epic historical films about warriors fighting with honour against overwhelming odds. Braveheart in Scotland, Last Samurai in Japan.', null); # Braveheart -> Last Samurai

-- Miscellaneous strong pairs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 280270, 8, 'orimor25', 'Both are films about underdogs who refuse to give up when everything is stacked against them. Shawshank and Rocky are the two greatest underdog stories in cinema.', null); # Shawshank -> Rocky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (67388, 270971, 7, 'orimor25', 'Both Scorsese films about competitive masculinity. Color of Money through pool, Raging Bull through boxing. Same director exploring the same obsessive drive.', null); # Color of Money -> Raging Bull
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (253010, 318388, 7, 'orimor25', 'Both are road/chase films set in Texas with morally complex protagonists. A Perfect World and Sugarland Express share Spielberg/Eastwood''s interest in fugitives with humanity.', null); # Perfect World -> Sugarland Express
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (350189, 218219, 7, 'orimor25', 'Both are Japanese animated films with gothic/mythological settings and morally complex characters. Vampire Hunter D and Mononoke are the darker side of anime storytelling.', null); # Vampire Hunter D -> Mononoke
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (33492, 62460, 7, 'orimor25', 'Both are European films centred on food and romance. Bella Martha is a German chef falling in love, Chocolat is a French chocolatier doing the same.', null); # Bella Martha -> Chocolat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 333856, 7, 'orimor25', 'Both are visually spectacular love stories that prioritise emotion over realism. Moulin Rouge and Titanic are the two most maximalist romances of their era.', null); # Moulin Rouge -> Titanic
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 359297, 6, 'orimor25', 'Both are alien invasion blockbusters but Independence Day plays it for spectacle while War of the Worlds goes for genuine fear. Same genre, different goals.', null); # Independence Day -> War of the Worlds
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313160, 13547, 8, 'orimor25', 'Both are documentary looks at legendary directors in their earliest stages. Kubrick: A Life in Pictures and Amblin'' show genius before the world noticed.', null); # Kubrick doc -> Amblin'
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185704, 181766, 7, 'orimor25', 'Both are Scorsese films about spiritual belief and its costs. Last Temptation explores Christianity, Kundun explores Buddhism. Same reverence, different traditions.', null); # Last Temptation -> Kundun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (230947, 7842, 8, 'orimor25', 'Both are Scorsese projects set in New York. New York Stories is an anthology, After Hours is a single night, both capture the city''s chaotic energy.', null); # New York Stories -> After Hours
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 370017, 7, 'orimor25', 'Both are early 2000s action films built around fast vehicles and big stunts with no pretensions about what they are. Same target audience, same energy.', null); # Fast and Furious -> XXX

-- NOT GOOD YET REASONABLE RECOMMENDATIONS 
-- Bad sequels vs originals
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30952, 2, 'orimor25', 'Both are Batman films but the comparison ends there. Begins is grounded realism, Batman and Robin is neon camp. Same character, opposite quality.', null); # Batman Begins -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30952, 2, 'orimor25', 'Burton''s Batman was dark and operatic. Batman and Robin is garish and embarrassing. The franchise fell off a cliff between these two.', null); # Batman 1989 -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10945, 3, 'orimor25', 'Both are Alien franchise films but Alien 3 destroyed everything the first two built. Same universe, completely different quality and care.', null); # Alien -> Alien 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 10945, 3, 'orimor25', 'Aliens is one of the best sequels ever made. Alien 3 killed off the surviving characters in the opening credits. Same franchise, devastating quality drop.', null); # Aliens -> Alien 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311040, 4, 'orimor25', 'Spider-Man launched a franchise. Spider-Man 3 buried it under too many villains and not enough focus. Same director with diminishing returns.', null); # Spider-Man -> Spider-Man 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311040, 3, 'orimor25', 'Spider-Man 2 elevated the genre. Spider-Man 3 crammed in Venom, Sandman, and Harry at once and gave none of them the space they needed.', null); # Spider-Man 2 -> Spider-Man 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280305, 3, 'orimor25', 'Rocky is a masterpiece about dignity. Rocky V took the same character back to the streets and wasted the opportunity with a weak new rival.', null); # Rocky -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280306, 2, 'orimor25', 'Rocky is one of the greatest sports films ever made. Rocky VI is a mislabelled entry that should not exist in the same franchise.', null); # Rocky -> Rocky VI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313474, 3, 'orimor25', 'Empire is the peak of Star Wars. Phantom Menace is the most disappointing entry. Same universe but the prequel never captures the magic of the original.', null); # Empire -> Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313476, 3, 'orimor25', 'Empire is mythological storytelling at its best. Attack of the Clones is a romance on Naboo that never earns the emotional weight it aims for.', null); # Empire -> Attack of the Clones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159167, 3, 'orimor25', 'Raiders defined adventure cinema. Indiana Jones 4 put him in a fridge and introduced aliens. Same character, completely different quality.', null); # Raiders -> Indy 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159167, 3, 'orimor25', 'Last Crusade closed the trilogy perfectly. Indiana Jones 4 reopened it with a premise that does not fit the world the original trilogy built.', null); # Last Crusade -> Indy 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 86263, 2, 'orimor25', 'GoldenEye reinvented Bond with intelligence. Die Another Day undid all of it with an invisible car and an ice palace. Same actor, opposite trajectories.', null); # GoldenEye -> Die Another Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 218808, 2, 'orimor25', 'From Russia with Love is grounded espionage. Moonraker sends Bond to space. Same franchise, completely different relationship with reality.', null); # From Russia with Love -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 85871, 4, 'orimor25', 'Goldfinger is peak Connery Bond. Diamonds Are Forever is visibly tired Connery going through the motions. Same actor, same character, different levels of engagement.', null); # Goldfinger -> Diamonds Are Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188510, 4, 'orimor25', 'Lethal Weapon established the buddy cop genre. Lethal Weapon 3 settled into formula and replaced edge with toilet humour. The chemistry survives but the writing does not.', null); # LW -> LW3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188511, 3, 'orimor25', 'Lethal Weapon is a sharp action film. Lethal Weapon 4 is an overstuffed franchise entry that wastes Jet Li and has run completely out of ideas.', null); # LW -> LW4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 238073, 4, 'orimor25', 'Ocean''s Eleven is an elegant heist film. Ocean''s Twelve is convoluted for the sake of it. Same cast, much less clarity in the story.', null); # Ocean's 11 -> Ocean's 12
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 256631, 4, 'orimor25', 'Curse of the Black Pearl is a perfectly self-contained adventure. Pirates 2 extends the story but spins its wheels badly in the middle third.', null); # Pirates 1 -> Pirates 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215879, 3, 'orimor25', 'Mission Impossible is a smart thriller. MI2 is a John Woo action film with no brain underneath the stunts. Same franchise, completely different ambitions.', null); # MI -> MI2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312152, 3, 'orimor25', 'Spy Kids is inventive family filmmaking. Spy Kids 3D abandoned story for a gimmick that overwhelmed everything else. The franchise ran out of ideas fast.', null); # Spy Kids -> Spy Kids 3D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312151, 4, 'orimor25', 'Spy Kids 1 had tight charm. Spy Kids 2 went bigger but lost the focus that made the original work. The island creatures are imaginative but the plot is not.', null); # Spy Kids -> Spy Kids 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 5, 'orimor25', 'Shrek is iconic and original. Shrek 2 is entertaining but slightly less original. If you loved the first you will enjoy the second but not as much.', null); # Shrek -> Shrek 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139650, 4, 'orimor25', 'Prisoner of Azkaban is the creative peak of the HP series. Chamber of Secrets is the most formulaic entry. Both set in Hogwarts but the directorial vision is worlds apart.', null); # Azkaban -> Chamber of Secrets
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280281, 280284, 5, 'orimor25', 'Rocky II is grounded drama. Rocky IV is Cold War propaganda with a training montage. Same character, completely different tone and ambition.', null); # Rocky II -> Rocky IV
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 280282, 5, 'orimor25', 'Rocky IV and Rocky III are both the more commercial, less serious entries. Both work as entertainment but neither reaches the emotional depth of the first two.', null); # Rocky IV -> Rocky III

-- Same actor, wildly different quality
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 47130, 4, 'orimor25', 'Both are films about New York night workers losing their grip on sanity. Taxi Driver is De Niro at his peak, Bringing Out the Dead is Cage in a more uneven film.', null); # Taxi Driver -> Bringing Out the Dead
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 230963, 4, 'orimor25', 'Both Scorsese-De Niro collaborations but Goodfellas is a masterpiece and New York, New York is an uneven musical experiment. Same partnership, different results.', null); # Goodfellas -> New York, New York
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 340652, 3, 'orimor25', 'Both are ancient world epics with large-scale battles. Gladiator finds its emotional core, Troy loses its characters in spectacle. Same genre, different depth.', null); # Gladiator -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 200864, 3, 'orimor25', 'Both are light entertainment with charming leads but Catch Me If You Can has Spielberg''s craft behind it. Maid in Manhattan is a thin template in comparison.', null); # Catch Me If You Can -> Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 292671, 3, 'orimor25', 'Both feature protagonists dealing with alternate versions of themselves. Fight Club executes the concept brilliantly, Secret Window compresses it too aggressively.', null); # Fight Club -> Secret Window
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 59578, 5, 'orimor25', 'Both Burton-Depp films about eccentric outsiders. Scissorhands found the perfect emotional balance, Chocolate Factory has the style but not quite the heart.', null); # Scissorhands -> Charlie
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 118367, 4, 'orimor25', 'Both are Tarantino-connected anthology films. Pulp Fiction perfected the format, Four Rooms is uneven with only the Tarantino and Rodriguez segments working.', null); # Pulp Fiction -> Four Rooms
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 283410, 3, 'orimor25', 'Roberts and Gere reunited but Runaway Bride never recaptures Pretty Woman''s chemistry. Same stars, same genre, much less magic the second time.', null); # Pretty Woman -> Runaway Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (14132, 14157, 3, 'orimor25', 'Both American Pie sequels reuniting the original cast. Pie 2 was formulaic, American Reunion was nostalgia without substance. Diminishing returns with each entry.', null); # American Pie 2 -> American Reunion
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46878, 283410, 4, 'orimor25', 'Both are romantic comedy sequels that fail to recapture the original''s charm. Bridget Jones 2 and Runaway Bride both settle into predictable formula.', null); # Bridget Jones 2 -> Runaway Bride

-- Surface similarity, different tone/quality
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 100130, 4, 'orimor25', 'Both are Spielberg WWII films but Schindler''s List is a masterpiece and Empire of the Sun is a more patient, less emotionally direct film. Same era, different impact.', null); # Schindler's List -> Empire of the Sun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 350424, 3, 'orimor25', 'Both are 1990s/2000s films that play with reality and identity. Pulp Fiction does it through structure, Vanilla Sky does it through dream logic. One succeeds far more than the other.', null); # Pulp Fiction -> Vanilla Sky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 1390, 2, 'orimor25', 'Both are early Spielberg blockbusters but Jaws is a masterclass in suspense and 1941 is an exhausting comedy that sacrifices story for noise.', null); # Jaws -> 1941
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 21213, 4, 'orimor25', 'Both are Spielberg sci-fi films about a being trying to find its way home. E.T. achieves it with economy, AI meanders through a bloated second act to get there.', null); # E.T. -> AI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 292671, 3, 'orimor25', 'Both are psychological thrillers with unreliable protagonists. Memento executes the concept brilliantly while Secret Window rushes through it without enough depth.', null); # Memento -> Secret Window
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 233058, 4, 'orimor25', 'Both are dark thrillers about obsession and hidden evil. Se7en is relentlessly intense, Ninth Gate is atmospheric but lacks the same urgency.', null); # Se7en -> Ninth Gate
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (306032, 178994, 3, 'orimor25', 'Both are ensemble crime films with overlapping storylines. Snatch does it with wit and precision, Knockaround Guys has the cast but not the script.', null); # Snatch -> Knockaround Guys
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30965, 3, 'orimor25', 'Both are Batman films but Begins redefined the character while Forever never found its tone between dark and campy. Same Gotham, different levels of commitment.', null); # Batman Begins -> Batman Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 340652, 3, 'orimor25', 'Both are epic war films with massive battle sequences. Saving Private Ryan finds humanity in chaos, Troy gets lost in spectacle without enough characters to anchor it.', null); # Saving Private Ryan -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 1121, 3, 'orimor25', 'Both are Ridley Scott historical epics. Gladiator found its emotional core, 1492 is ambitious but slow and never connects on the same human level.', null); # Gladiator -> 1492
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 200864, 4, 'orimor25', 'Both are early 2000s romantic comedies with charming leads. How to Lose a Guy has a clever premise, Maid in Manhattan has a thinner one in the same template.', null); # How to Lose a Guy -> Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 1038, 4, 'orimor25', 'Both are fun, light films aimed at a similar audience. 10 Things has genuine wit from its Shakespeare source, 13 Going on 30 is harmless but less sharp.', null); # 10 Things -> 13 Going On 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 264157, 3, 'orimor25', 'Both are coming-of-age comedies but Clueless is a sharp satire of high school culture. Princess Diaries 2 falls back on the same fish-out-of-water formula without adding anything.', null); # Clueless -> Princess Diaries 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (350424, 69812, 4, 'orimor25', 'Both are conspiracy-tinged thrillers starring major leads. Vanilla Sky has ambition but uneven execution, Conspiracy Theory has Gibson and Roberts in a premise that deflates at the end.', null); # Vanilla Sky -> Conspiracy Theory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256839, 370017, 4, 'orimor25', 'Both are Vin Diesel action vehicles. Pitch Black uses him in a smart sci-fi setting, XXX uses him in a disposable action template. Same star, different ambition.', null); # Pitch Black -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 8183, 4, 'orimor25', 'Both Scorsese period films but Casino is propulsive and electric while Age of Innocence is restrained and meditative. Fans of one may find the other too different in pace.', null); # Casino -> Age of Innocence
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 270628, 2, 'orimor25', 'Both are films about hope under terrible circumstances. Shawshank earns its emotion honestly, Radio Flyer handles a painful premise with too much sentimentality.', null); # Shawshank -> Radio Flyer
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (192702, 189403, 5, 'orimor25', 'Both are Timothy Dalton Bond entries. Living Daylights reinvented the character, Licence to Kill pushed him into generic 1980s action territory. Same actor, different success.', null); # Living Daylights -> Licence to Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335336, 368418, 5, 'orimor25', 'Both are middle-era Brosnan Bond films. Tomorrow Never Dies is slick but hollow, World Is Not Enough wastes Marceau. Both are watchable and forgettable.', null); # Tomorrow Never Dies -> TWINE
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (192514, 354178, 4, 'orimor25', 'Both are Roger Moore Bond films. Live and Let Die has Caribbean charm, View to a Kill wastes Walken on thin material. Same era, declining quality.', null); # Live and Let Die -> View to a Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (332065, 372233, 5, 'orimor25', 'Both are mid-1960s Connery Bond spectacles. Thunderball drags underwater, You Only Live Twice prioritises sets over story. Neither reaches the level of Goldfinger.', null); # Thunderball -> You Only Live Twice
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117314, 203649, 5, 'orimor25', 'Both are Roger Moore Bond entries with scenic locations and competent but unmemorable villains. Neither rises above the middle tier of the franchise.', null); # For Your Eyes Only -> Man with Golden Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218808, 86263, 5, 'orimor25', 'Both are Bond films that abandoned reality entirely. Moonraker went to space, Die Another Day went invisible. Neither works as a thriller because neither is grounded.', null); # Moonraker -> Die Another Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (164572, 120506, 4, 'orimor25', 'Both are crime thrillers set in gritty period atmospheres. Jackie Brown is Tarantino at his most character driven, From Hell substitutes atmosphere for depth.', null); # Jackie Brown -> From Hell
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113506, 34077, 4, 'orimor25', 'Both are biographical dramas with Depp/Blanchett about creative figures. Finding Neverland earns its sentiment, Benjamin Button feels more like a technical exercise than a story.', null); # Finding Neverland -> Benjamin Button
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 271344, 3, 'orimor25', 'Both are films about unexpected family guardianship. Lilo and Stitch treats it with real emotional honesty, Raising Helen turns it into a formulaic comedy.', null); # Lilo & Stitch -> Raising Helen
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 120506, 5, 'orimor25', 'Both are dark, fog-drenched period horror films. Sleepy Hollow has Burton''s visual magic, From Hell has atmosphere but lacks the same creative personality.', null); # Sleepy Hollow -> From Hell
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30951, 30962, 5, 'orimor25', 'Both are animated Batman spinoff films. SubZero gives Fries nuanced writing, Batman Beyond is a different setting entirely. Related but serving different audiences.', null); # SubZero -> Batman Beyond
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 259826, 4, 'orimor25', 'Both are Spielberg-produced family films with supernatural elements. Hook aims for childhood wonder, Poltergeist aims for childhood terror. Same producer, opposite intentions.', null); # Hook -> Poltergeist
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (74259, 105851, 2, 'orimor25', 'Both are campy comedies that lean into genre pastiche. Cry-Baby does it with John Waters'' precision, Exit to Eden squanders every opportunity its premise creates.', null); # Cry-Baby -> Exit to Eden
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34104, 245699, 4, 'orimor25', 'Both are romantic comedies about unconventional relationships. Benny and Joon treats its characters with genuine care, Overboard relies on a premise with dated ethics.', null); # Benny & Joon -> Overboard
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (200521, 21213, 4, 'orimor25', 'Both are ambitious three-hour films with sprawling emotional scope. Magnolia earns its bold choices, AI loses focus in its bloated second act.', null); # Magnolia -> AI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (231917, 308057, 5, 'orimor25', 'Both are early Spielberg TV projects. Night Gallery shows his instinct for dread, Something Evil has atmosphere but less directorial personality.', null); # Night Gallery -> Something Evil
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (41518, 258948, 3, 'orimor25', 'Both are early 1990s films about characters drawn into dangerous lifestyles. Blow has period detail and Depp''s restraint, Poison Ivy has a thin script held together by casting alone.', null); # Blow -> Poison Ivy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (257744, 31715, 4, 'orimor25', 'Both are ensemble dramas about relationships with emotional depth. Playing by Heart has genuine warmth across its ensemble, Beaches is aimed narrower and more sentimental.', null); # Playing by Heart -> Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (308025, 69812, 4, 'orimor25', 'Both are thrillers involving unlikely romantic tensions under dangerous circumstances. Someone to Watch Over Me commits to its premise, Conspiracy Theory deflates at the resolution.', null); # Someone to Watch Over Me -> Conspiracy Theory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (20253, 350424, 4, 'orimor25', 'Both are surrealist films about characters drifting between dreams and reality. Arizona Dream does it with Kusturica''s warmth, Vanilla Sky does it with more polish but less soul.', null); # Arizona Dream -> Vanilla Sky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235615, 114955, 5, 'orimor25', 'Both are 1980s dramas about young men navigating complicated relationships with older mentors. Nothing in Common has more emotional honesty, Flamingo Kid is lighter and more conventional.', null); # Nothing in Common -> Flamingo Kid

-- Additional good recommendations
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176712, 164572, 7, 'orimor25', 'Kill Bill Vol 2 and Jackie Brown are both Tarantino films that slow down and let the characters breathe. His most patient work in both cases.', null); # Kill Bill 2 -> Jackie Brown
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 271095, 8, 'orimor25', 'Temple of Doom and Raiders are both Indiana Jones adventures with completely different settings. Temple goes darker and weirder but the adventure energy is the same.', null); # Temple of Doom -> Raiders
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 117874, 7, 'orimor25', 'Both are Hanks films about isolated men finding warmth in unusual circumstances. The Terminal in an airport, Forrest Gump across American history.', null); # Terminal -> Forrest Gump
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215876, 7, 'orimor25', 'Both are 1980s/90s action films driven by military spectacle and Tom Cruise''s screen presence. Top Gun in the air, Mission Impossible on the ground.', null); # Top Gun -> MI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (25192, 123849, 7, 'orimor25', 'Both Scorsese-DiCaprio period epics about obsessive American figures. The Aviator in Hollywood, Gangs of New York in 19th century Manhattan.', null); # Aviator -> Gangs of NY
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56282, 97727, 7, 'orimor25', 'Both are visually distinctive films about outsiders who experience the world differently. Cashback freezes time, Edward Scissorhands reshapes suburbia. Both use visual metaphor as storytelling.', null); # Cashback -> Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 289109, 8, 'orimor25', 'Both Hanks-led Spielberg films that use American history as a backdrop for deeply personal stories. Forrest Gump spans decades, Ryan focuses on a single mission.', null); # Forrest Gump -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159175, 7, 'orimor25', 'Last Crusade and Temple of Doom are the two sequels to Raiders. Crusade adds Connery, Temple goes darker, both are worth watching for any Indiana Jones fan.', null); # Last Crusade -> Temple of Doom
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 326155, 8, 'orimor25', 'Both are films about alienated men driven to extreme action by modern society. Fight Club uses satire, Taxi Driver uses realism, both are uncomfortable and essential.', null); # Fight Club -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 96593, 7, 'orimor25', 'Both are films about humans forming bonds with alien beings in American settings. Men in Black is comedy, E.T. is drama, but both treat the alien with genuine warmth.', null); # MIB -> E.T.
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 247579, 6, 'orimor25', 'Both Fincher thrillers with dark atmospheres and contained, claustrophobic tension. Se7en is the masterpiece, Panic Room is the smaller scale companion piece.', null); # Se7en -> Panic Room
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32707, 20253, 6, 'orimor25', 'Both are films about artists and outsiders set against politically charged backdrops. Before Night Falls in Cuba, Arizona Dream in American surrealism. Both star unconventional leads.', null); # Before Night Falls -> Arizona Dream

-- Additional not-good-yet-reasonable recommendations
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30967, 30965, 3, 'orimor25', 'Batman Returns doubled down on Burton''s gothic vision. Batman Forever tried to lighten the tone and lost the identity in the process. Same franchise, different commitments.', null); # Batman Returns -> Batman Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 350189, 4, 'orimor25', 'Both are action films with strong anime influences and stylized violence. Kill Bill draws from the tradition directly, Vampire Hunter D lives inside it. Same visual DNA, different execution levels.', null); # Kill Bill Vol 1 -> Vampire Hunter D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 1121, 3, 'orimor25', 'Both are epic historical films about outsiders arriving in foreign cultures. Last Samurai finds emotional depth, 1492 is ambitious but never connects on the same level.', null); # Last Samurai -> 1492
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 300230, 4, 'orimor25', 'Both are animated films from studios that defined the genre. Toy Story launched Pixar with originality, Shrek 2 is entertaining DreamWorks but less inventive than the first.', null); # Toy Story -> Shrek 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313474, 5, 'orimor25', 'Revenge of the Sith and Phantom Menace are the best and worst of the prequels. Both Lucas directed but separated by a huge gap in emotional weight and story focus.', null); # Revenge of Sith -> Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280282, 280305, 4, 'orimor25', 'Rocky III and Rocky V are both lesser entries. III has Mr T and entertainment value, V took Rocky back to the streets and wasted the opportunity. Neither reaches the first two.', null); # Rocky III -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215879, 3, 'orimor25', 'Both are action spectacles carried by star power and kinetic direction. Top Gun has genuine aerial thrills, MI2 has Woo''s stunts but nothing underneath them.', null); # Top Gun -> MI2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 340652, 4, 'orimor25', 'Both are ancient/medieval epics with large-scale battle sequences. Braveheart finds its characters in the chaos, Troy lets spectacle overwhelm everything else.', null); # Braveheart -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 46878, 4, 'orimor25', 'Both are romantic comedy sequels/entries with attractive leads and predictable plots. How to Lose a Guy has a cleverer premise, Bridget Jones 2 has settled into formula.', null); # How to Lose a Guy -> Bridget Jones 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 233058, 4, 'orimor25', 'Both are dark thrillers about protagonists drawn into mysterious conspiracies. The Game maintains its tension perfectly, Ninth Gate builds atmosphere but lacks the same payoff.', null); # The Game -> Ninth Gate
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (100130, 14477, 5, 'orimor25', 'Both are Spielberg historical dramas about injustice. Empire of the Sun follows a child in WWII, Amistad follows a courtroom battle. Same director, different emotional access points.', null); # Empire of the Sun -> Amistad
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159665, 185628, 4, 'orimor25', 'Both are WWII-era films with outsiders embedded in foreign cultures. Inglourious Basterds reinvents history with wit, Last Samurai plays it straight with mixed results.', null); # Inglourious Basterds -> Last Samurai
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 280306, 2, 'orimor25', 'Rocky IV is ridiculous Cold War propaganda but it works emotionally. Rocky VI is a mislabelled entry that no one asked for. The franchise had clearly run its course.', null); # Rocky IV -> Rocky VI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (174953, 70959, 5, 'orimor25', 'Both are animated films with striking visual identities. Nausicaa has environmental depth and urgency, Corpse Bride has beautiful design but a thinner story underneath.', null); # Nausicaa -> Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 181766, 3, 'orimor25', 'Both Scorsese films but Casino is propulsive crime filmmaking, Kundun is deeply meditative and slow. Fans of one may not have the patience for the other at all.', null); # Casino -> Kundun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 74259, 5, 'orimor25', 'Both are quirky films about outsiders in American settings. Edward Scissorhands is a fairy tale, Cry-Baby is a satire. Similar tone but different emotional weight.', null); # Edward Scissorhands -> Cry-Baby
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319613, 218808, 3, 'orimor25', 'Both are superhero/Bond sequels from the same era with grand-scale villains. Superman II uses them well, Moonraker takes Bond too far from reality to work.', null); # Superman II -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 313479, 5, 'orimor25', 'Both are epic trilogy conclusions with massive final battles. Return of the King nails every emotional beat, Return of the Jedi is weakened by the Ewoks but has a strong throne room scene.', null); # ROTK -> ROTJ
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (67395, 31715, 4, 'orimor25', 'Both are emotional dramas about female friendships enduring through hardship. Color Purple has depth and literary weight, Beaches is more sentimental and narrower in scope.', null); # Color Purple -> Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139654, 139653, 5, 'orimor25', 'Both are later HP entries with darker themes. Order of the Phoenix has Umbridge and political weight, Half-Blood Prince has the cave scene but the teen romance is a distraction.', null); # Order Phoenix -> Half-Blood Prince
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 332065, 5, 'orimor25', 'Both are early Connery Bond films. Dr No is grounded and tight, Thunderball drags between impressive but overlong underwater sequences.', null); # Dr No -> Thunderball
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 308057, 4, 'orimor25', 'Both Spielberg projects involving suburban supernatural threats. E.T. is a masterpiece of childhood wonder, Something Evil is a minor TV film with atmosphere but limited depth.', null); # E.T. -> Something Evil
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 185704, 3, 'orimor25', 'Both are Scorsese films that provoked strong reactions on release. Goodfellas was universally praised, Last Temptation was controversial and far more divisive. Same director at different risk levels.', null); # Goodfellas -> Last Temptation
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 158999, 4, 'orimor25', 'Both are ensemble blockbusters with star-packed casts. Ocean''s Eleven is cool and effortless, Independence Day is loud and absurd. Same scale, very different intelligence.', null); # Ocean's 11 -> Independence Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34104, 62460, 5, 'orimor25', 'Both are gentle romantic films about unconventional people finding connection. Benny and Joon has genuine care for its characters, Chocolat has warmth but never fully commits to its direction.', null); # Benny & Joon -> Chocolat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (177369, 270971, 7, 'orimor25', 'Both Scorsese-De Niro character studies of men consumed by obsession. King of Comedy is obsessed with fame, Raging Bull is obsessed with winning. Same volcanic intensity.', null); # King of Comedy -> Raging Bull
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313474, 313476, 5, 'orimor25', 'Phantom Menace and Attack of the Clones are the two weakest prequel entries. Both have memorable action sequences dragged down by dialogue and romance that never work.', null); # Phantom Menace -> Attack of the Clones
